Querdos\QFileEncryptionBundle\Entity\QFile:
    type:             entity
    table:            qfe_file
    repositoryClass:  Querdos\QFileEncryptionBundle\Repository\QFileRepository
    id:
        id:
            type:         integer
            id:           true
            generator:
                strategy: AUTO
    fields:
        original_name:
            type:         string
            length:       255
            unique:       false
            nullable:     false
        filename:
            type:         string
            length:       255
            unique:       true
            nullable:     false
        path:
            type:         string
            length:       255
            unique:       false
            nullable:     false

    lifecycleCallbacks: {}
