services:
    qfe.manager.qkey:
        class: Querdos\QFileEncryptionBundle\Manager\QKeyManager
        calls:
            - [ setRepository,    ['@qfe.repository.qkey'] ]
            - [ setEntityManager, ['@doctrine.orm.entity_manager']]
