services:
    q_fe.util.asymetric:
        class:      Querdos\QFileEncryptionBundle\Util\AsymetricUtil
        calls:
            - [ setKernel,          [ '@kernel' ]]
            - [ setQKeyManager,     [ '@qfe.manager.qkey']]

    q_fe.util.log:
        class: Querdos\QFileEncryptionBundle\Util\LogUtil
        calls:
            - [ setLogError,         [ '@kernel', '%q_file_encryption.logs_dir%' ]]
